[build] multiav docker builds should fail if eicar scan fails

diff --git a/build/docker/Dockerfile.kaspersky b/build/docker/Dockerfile.kaspersky
--- a/build/docker/Dockerfile.kaspersky
+++ b/build/docker/Dockerfile.kaspersky
@@ -1,10 +1,10 @@
 FROM debian:stretch-slim
 LABEL maintainer="https://github.com/saferwall"
-LABEL version="0.0.2"
+LABEL version="0.0.3"
 LABEL description="Kaspersky Anti-Virus for Linux File Servers in a docker container"
 # https://help.kaspersky.com/KES4Linux/10.1.1/en-us/177085.htm
 
-# Vars
+# Environment variable.
 ENV KASPERSKY_VERSION	10.1.1.6421
 ENV KASPERSKY_BIN 		/opt/kaspersky/kesl/bin/kesl-control
 ENV KASPERSKY_SETUP 	/opt/kaspersky/kesl/bin/kesl-setup.pl
@@ -12,42 +12,40 @@ ENV KASPERSKY_URL 		https://products.s.kaspersky-labs.com/endpoints/keslinux10/$
 ENV KASPERSKY_TMP		/tmp/kaspersky
 ENV KASPERSKY_LICENSE   /opt/kaspersky/license.key
 
-# Install dependencies
-RUN apt-get update \
-	&& apt-get install wget perl locales procps -y 
 
-# Install Kaspersky
+# Install dependencies.
+RUN apt-get update \
+	&& apt-get install -qq wget perl locales procps
+
+# Install Kaspersky.
 RUN mkdir -p $KASPERSKY_TMP \
-	&& wget -N $KASPERSKY_URL -P $KASPERSKY_TMP \
+	&& wget -q -N $KASPERSKY_URL -P $KASPERSKY_TMP \
 	&& dpkg -i $KASPERSKY_TMP/kesl_10.1.1-6421_amd64.deb
 
-# Set up locales
+# Setting up locales.
 RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
 	&& locale-gen
-
-# Setup locals for kaspersky to run properly.
 ENV LANG en_US.UTF-8  
 ENV LANGUAGE en_US:en  
 ENV LC_ALL en_US.UTF-8 
 
-# Configure it
+# Configure it.
 ADD install.conf install.conf
-RUN $KASPERSKY_SETUP --autoinstall=install.conf; exit 0
+RUN $KASPERSKY_SETUP --autoinstall=install.conf || true
 
-# # Install license key
+# Install license key
 COPY kaspersky.license.key $KASPERSKY_LICENSE
 RUN service kesl-supervisor start \
 	&& $KASPERSKY_BIN --install-active-key $KASPERSKY_LICENSE
 
-# Add the EICAR Anti-Virus Test File
+# Download EICAR Anti-Virus Test File.
 ADD http://www.eicar.org/download/eicar.com.txt eicar
 
-# Test detection
+# Performs a simple detection test.
 RUN service kesl-supervisor start \
 	&& $KASPERSKY_BIN --scan-file eicar \
-	&& $KASPERSKY_BIN -E --query "EventType=='ThreatDetected'" \
-	; exit 0
+	&& $KASPERSKY_BIN -E --query "EventType=='ThreatDetected'" || true
 
-# Clean up
+# Clean up.
 RUN rm -rf $KASPERSKY_TMP \
 	&& rm -rf /var/lib/apt/lists/*
